In [ ]:
#Name-Sara Potey
#PRN-25070123102
#Experiment-9
#Aim- Study of Numpy Library

In [3]:
#Declaration of Numpy
import numpy as np
a=np.array([1,10,20,30,40,50,500])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

#Dimension of Array:
print(a.ndim)
print(b.ndim)

print(a.shape)
print(b.shape)

print(a.dtype)
print(b.dtype)

# In-built functions using Numpy.
np.zeros((2,3))

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
int64
int64


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
print(b*2)
print(a+5)

[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [ ]:
np.mean(a)

np.float64(93.0)

In [ ]:
np.median(a)

np.float64(30.0)

In [ ]:
np.min(a)

np.int64(1)

In [ ]:
np.sum(a)

np.int64(651)

In [ ]:
np.max(a)

np.int64(500)